.

diff --git a/attached/set_app b/attached/set_app
--- a/attached/set_app
+++ b/attached/set_app
@@ -8,21 +8,34 @@ NC='\033[0m' # No color (reset)
 
 # Navigate to the project directory and set environment variables
 cd /CarBnR_v4
-export CARBNR_MYSQL_USER=carbnr_dev \
-       CARBNR_MYSQL_PWD=carbnr_dev_pwd \
-       CARBNR_MYSQL_HOST=localhost \
-       CARBNR_MYSQL_DB=carbnr_dev_db \
-       CARBNR_TYPE_STORAGE=db
+# Specify the location of the .env file
+ENV_FILE="/CarBnR_v4/.env"
+
+# Check if the .env file exists
+if [ -f "$ENV_FILE" ]; then
+  # Load variables from the .env file
+  set -a
+  source "$ENV_FILE"
+  set +a
+  echo -e "${GREEN}[*] Environment variables loaded successfully.${NC}"
+else
+  echo -e "${RED}[-] Error: .env file not found at $ENV_FILE${NC}"
+  exit 1
+fi
+
+# Now the variables are available
+echo "MySQL User: $CARBNR_MYSQL_USER"
 
 # Store current directory
 pwd_path=$(pwd)
+sleep 1
 
 # Start gunicorn processes in tmux sessions
 tmux new-session -d 'gunicorn --bind 0.0.0.0:5002 api.v1.app:app'
 tmux new-session -d 'gunicorn --bind 0.0.0.0:5000 carapp.select_cars:app'
 
 # Wait for processes to start
-sleep 2
+sleep 1
 
 # Check and report the status of the process on port 5000
 pids_5000=$(lsof -t -i :5000 | tr '\n' ' ')  # Capture all PIDs in one line
